### PR TITLE
Jazzy docs

### PR DESCRIPTION
**Pull request by xtopolis**
## Issue Link :link:
 <ul>
   <li> Is this a bug fix or a feature? **Feature**</li>
   <li> Does it break any existing functionality? **Unit Tests still pass**</li>
</ul>

## Goals of this PR :tada:

- Why is the change important? hacktoberfest
- What does this fix? https://github.com/intuit/CardParts/issues/58
- How far has it been tested? N/A
- [x] Remove docs/ from gitignore
- This is where the magic happens: `.jazzy.yaml`
- Preview: https://cardparts.surge.sh

 </ul>
 
## How Has This Been Tested :mag:

Please let us know if you have tested your PR and if we need to reproduce the issues. Also, please let us know if we need any relevant information for running the tests.

<ul>
 <li>N/A</li>
</ul>

## Test Configuration :space_invader:

<ul>
 <li> Xcode version: 10.3</li>
</ul>

## Things to check on :dart:

 - [x] My Pull Request code follows the coding standards and styles of the project 
 - [N/A] I have worked on unit tests and reviewed my code to the best of my ability 
 - [x] I have used comments to make other coders understand my code better 
 - [x] My changes are good to go without any warnings 
 - [N/A] I have added unit tests both for the happy and sad path 
 - [x] All of my unit tests pass successfully before pushing the PR 
 - [x] I have made sure all dependent downstream changes impacted by my PR are working

### CODE REVIEW

**Comment by xtopolis** [comment]
@croossin Need to do a little review, but it's at 100% documentation. A lot of it is redundant property name, or self explanatory property comments. Anything else you'd like done?

**Comment by xtopolis** [comment]
Ready for any final comments and whether or not I should add in build step or leave it to you.

**Comment by croossin** [comment]
Would be awesome to have as a build step @xtopolis - but how much of a lift is that?

**Comment by croossin** [comment]
@xtopolis Is it hard to get this in the build pipeline?

**Comment by xtopolis** [comment]
I'll be able to look into it by end of week/this weekend, sorry for the delay.

**Comment by xtopolis** [comment]
@croossin Merge away if ready

**Pull request closed without merging**
