### PR TITLE
Adds custom states to CardParts

### PR DESCRIPTION
**Pull request by dtumer**
Changes the definition of CardState to be a struct instead of an enum and its default states are now defined as strings. Defining the states as Strings allows for more customization by giving developers the ability to create an extension of the CardState structure and adding any custom states they would like to define.

See #36 for more details

### CODE REVIEW

**Comment by bharathmurs** [comment]
I like it.

**Comment by croossin** [comment]
So this is definitely an API breaking change - so we should think about how we want to release this and in which version.  @dtumer I know you had a few other cards you wanted to add... so maybe let's make that a release, say `2.3.8` or `2.4.0` and then we will add this and cut a release for either `2.4.0` or `3.0.0`.  Thoughts @bharathmurs ?

**Comment by croossin** [comment]
Also, just so we note it: If we approve and merge this [pr](https://github.com/intuit/CardParts/pull/46) then we will need to update the example app since it still uses the old enum CardState

**Comment by croossin** [comment]
We have decided to continue enum route and a `.custom(String)` enum instead.  Will open another PR for those changes.

**Pull request closed without merging**
