### PR TITLE
Adding more capability for customizing gradients.

### PR DESCRIPTION
**Pull request by bharathmurs**

### CODE REVIEW

**Comment by lwdupont** [comment]
I need to take a look at the example app, but it would be nice to see some changes in there to show this functionality. Just a thought :)

**Comment by lwdupont** [comment]
Oh, no documentation needed to be updated?

**Comment by croossin** [comment]
@lwdupont Yes we were just chatting - we need to add the `ShadowCardTrait` to the README.  I also fully agree that we should add some more in depth examples to the Example app. Something I plan to do this week.

**Comment by croossin** [comment]
For reference: #6 and #7

**Pull request merged**
