### PR TITLE
Fix example to not use beta cocoapods

### PR DESCRIPTION
**Pull request by lwdupont**
Finally got around to fixing the CocoaPods beta issue.

### CODE REVIEW

**Comment by lwdupont** [comment]
@bharathmurs can you check this out? And maybe the Travis build issue? Haven't been able to figure it out yet.

**Comment by lwdupont** [comment]
@croossin Fixed it - have a look and make sure I didn't mess anything up :)

**Comment by lwdupont** [comment]
Thanks @bharathmurs !! 👍

**Comment by croossin** [comment]
Awesome @lwdupont !!! Thanks so much!

**Pull request merged**
